#!/usr/bin/env bash
# Generates THIRD-PARTY-NOTICES.md on stdout: a table of every third-party
# component this build ships (Go modules compiled into the backend, npm
# packages in the frontend's production build, the Go standard library
# itself), followed by each distinct licence text once. It does not
# judge licences — that is check-licenses.sh's job; this only records what
# shipped, deterministically (the same tree produces byte-identical output).
#
# Real use needs the network (to fetch lichen) and a buildable backend/
# under LICENSE_ROOT. generate-notices_test.sh overrides *_OUTPUT to fixed
# files instead, bypassing the tools entirely.

set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="${LICENSE_ROOT:-$(cd "$HERE/.." && pwd)}"
LICHEN_CMD="${LICHEN_CMD:-go run github.com/uw-labs/lichen@v0.1.7}"
LICENSE_CHECKER_CMD="${LICENSE_CHECKER_CMD:-npx --yes license-checker-rseidelsohn@5.0.1}"
WORK="$(mktemp -d)"; trap 'rm -rf "$WORK"' EXIT

# ── Gather: one line per Go module, "path|version|license|licensefile" ──────
if [[ -n "${LICHEN_NOTICES_OUTPUT:-}" ]]; then
  cp "$LICHEN_NOTICES_OUTPUT" "$WORK/go-lines.txt"
else
  tmp_bin="$WORK/backend-bin"
  ( cd "$ROOT/backend" && GOTOOLCHAIN="${GOTOOLCHAIN:-auto}" go build -o "$tmp_bin" ./cmd/server ) \
    || { echo "error: could not build $ROOT/backend/cmd/server" >&2; exit 2; }
  template='{{range .Modules}}{{.Module.Path}}|{{.Module.Version}}|{{range $i,$_ := .Module.Licenses}}{{if $i}};{{end}}{{.Name}}{{end}}|{{range .Module.Licenses}}{{.Path}}{{end}}
{{end}}'
  $LICHEN_CMD --template="$template" "$tmp_bin" > "$WORK/go-lines.txt" 2>/dev/null \
    || { echo "error: \$LICHEN_CMD failed to run" >&2; exit 2; }
fi

# ── Gather: npm production packages as JSON ({"name@ver": {licenses,...}}) ──
if [[ -n "${LICENSE_CHECKER_NOTICES_OUTPUT:-}" ]]; then
  cp "$LICENSE_CHECKER_NOTICES_OUTPUT" "$WORK/npm.json"
else
  ( cd "$ROOT/frontend" && $LICENSE_CHECKER_CMD --production --excludePrivatePackages --json ) > "$WORK/npm.json" 2>/dev/null \
    || { echo "error: \$LICENSE_CHECKER_CMD failed to run" >&2; exit 2; }
fi

# ── Gather: the Go standard library itself (lichen only reports imports) ────
# `go env GOROOT` alone reports the system default toolchain (which may not
# even have a LICENSE file — e.g. a distro package's install strips it) —
# only an actual toolchain-sensitive command like `go version` (run from the
# module directory, so it sees go.mod's requirement) makes GOTOOLCHAIN=auto
# switch to the one actually used to build the binary above; a later `go env`
# in the same subshell then reports that toolchain's real GOROOT.
if [[ -n "${GO_STDLIB_LICENSE:-}" ]]; then
  : # explicit override, keep as-is
else
  GO_STDLIB_LICENSE="$(
    cd "$ROOT/backend" && GOTOOLCHAIN="${GOTOOLCHAIN:-auto}" go version >/dev/null 2>&1
    GOTOOLCHAIN="${GOTOOLCHAIN:-auto}" go env GOROOT 2>/dev/null
  )/LICENSE"
fi
if [[ -n "${GO_STDLIB_VERSION:-}" ]]; then
  go_version="$GO_STDLIB_VERSION"
else
  # Same directory context as the GOROOT lookup above, so this reports the
  # toolchain actually used to build the binary, not the system default.
  go_version="$(cd "$ROOT/backend" && GOTOOLCHAIN="${GOTOOLCHAIN:-auto}" go version 2>/dev/null | awk '{print $3}')"
fi

# ── Build one TSV row per component: name<TAB>version<TAB>license<TAB>source<TAB>licensefile ──
entries="$WORK/entries.tsv"; : > "$entries"

while IFS='|' read -r path version license licensefile || [[ -n "$path" ]]; do
  [[ -z "$path" ]] && continue
  printf '%s\t%s\t%s\t%s\t%s\n' "$path" "$version" "$license" "Go module" "$licensefile" >> "$entries"
done < "$WORK/go-lines.txt"

for key in $(jq -r 'keys[]' "$WORK/npm.json"); do
  name="${key%@*}"; ver="${key##*@}"
  license="$(jq -r --arg k "$key" '.[$k].licenses // "Unknown"' "$WORK/npm.json")"
  repo="$(jq -r --arg k "$key" '.[$k].repository // ""' "$WORK/npm.json")"
  licensefile="$(jq -r --arg k "$key" '.[$k].licenseFile // ""' "$WORK/npm.json")"
  printf '%s\t%s\t%s\t%s\t%s\n' "$name" "$ver" "$license" "${repo:-Unknown}" "$licensefile" >> "$entries"
done

if [[ -f "$GO_STDLIB_LICENSE" ]]; then
  printf '%s\t%s\t%s\t%s\t%s\n' "go (standard library)" "$go_version" "BSD-3-Clause" "Go toolchain" "$GO_STDLIB_LICENSE" >> "$entries"
fi

sorted="$WORK/entries-sorted.tsv"
LC_ALL=C sort -t $'\t' -k1,1 "$entries" > "$sorted"

# ── Table ─────────────────────────────────────────────────────────────────
{
  echo '# Third-Party Notices'
  echo
  echo 'This build distributes the following third-party components, generated by'
  echo '`scripts/generate-notices.sh`.'
  echo 'It does not judge whether a licence is appropriate — that is'
  echo '`scripts/check-licenses.sh`'"'"'s job; this file only records what shipped.'
  echo
  echo '| Component | Version | Licence | Source |'
  echo '|---|---|---|---|'
} > "$WORK/out.md"

while IFS=$'\t' read -r name version license source _; do
  printf '| %s | %s | %s | %s |\n' "$name" "$version" "$license" "$source" >> "$WORK/out.md"
done < "$sorted"

# ── Licence texts: grouped by unique file content, one heading each ─────────
echo >> "$WORK/out.md"
echo '## Licence texts' >> "$WORK/out.md"

groups_dir="$WORK/groups"; mkdir -p "$groups_dir"
while IFS=$'\t' read -r name version license _ licensefile; do
  [[ -z "$licensefile" || ! -f "$licensefile" ]] && continue
  hash="$(sha256sum "$licensefile" | cut -d' ' -f1)"
  echo "$name $version" >> "$groups_dir/$hash.members"
  echo "$license" > "$groups_dir/$hash.license"
  cp "$licensefile" "$groups_dir/$hash.text"
done < "$sorted"

# Order groups by their earliest (alphabetically smallest) member, so the
# result depends only on the components involved, not on scan order.
: > "$WORK/group-order.txt"
shopt -s nullglob
for f in "$groups_dir"/*.members; do
  hash="$(basename "$f" .members)"
  first="$(LC_ALL=C sort "$f" | head -1)"
  printf '%s\t%s\n' "$first" "$hash" >> "$WORK/group-order.txt"
done
if [[ -s "$WORK/group-order.txt" ]]; then
  LC_ALL=C sort -t $'\t' -k1,1 "$WORK/group-order.txt" | while IFS=$'\t' read -r _ hash; do
    {
      echo
      echo "### $(cat "$groups_dir/$hash.license")"
      echo
      echo -n "Used by: "
      paste -sd, "$groups_dir/$hash.members" | sed 's/,/, /g'
      echo
      echo '```'
      cat "$groups_dir/$hash.text"
      echo '```'
    } >> "$WORK/out.md"
  done
fi

cat "$WORK/out.md"
